# -*- coding: utf-8 -*-
"""jrv2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W1FCmFhmGUKBqO3Cyw2bhuvfM3dkE7Gi
"""

# ============================================================================
# CELL 1: Install Dependencies
# ============================================================================
import sys
import subprocess

def install_packages():
    print("=" * 80)
    print("🚀 INSTALLING DEPENDENCIES")
    print("=" * 80)
    packages = [
        'numpy==2.0.2', 'pandas==2.1.4', 'torch', 'scikit-learn',
        'tqdm', 'pdfplumber', 'python-docx', 'python-jobspy',
        'sentence-transformers', 'groq',
    ]
    for package in packages:
        try:
            subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q', package])
            print(f"✓ {package.split('==')[0]}")
        except Exception:
            print(f"⚠ {package.split('==')[0]} (may need restart)")
    print("\n✅ Installation complete!\n")

# CELL 2: Mount Google Drive
# ============================================================================
from google.colab import drive
drive.mount('/content/drive')
print("\n✅ Google Drive mounted!")

# ============================================================================
# CELL 3: Imports
# ============================================================================
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import numpy as np
import pandas as pd
import json
import re
import os
import pickle
from collections import Counter
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from tqdm import tqdm
from datetime import datetime

# Install remaining libs inline (Colab style)
!pip install -q pdfplumber python-docx python-jobspy sentence-transformers groq

import pdfplumber
import docx
from jobspy import scrape_jobs
from sentence_transformers import SentenceTransformer
from google.colab import files

# ── Groq client ──────────────────────────────────────────────────────────────
from groq import Groq

# ⚠️  Set your Groq API key via env var GROQ_API_KEY or paste it below
GROQ_API_KEY = os.environ.get("GROQ_API_KEY", "apikey")   # <-- paste your key here if not using env var
GROQ_MODEL   = "llama-3.3-70b-versatile"   # best open model on Groq (128k ctx)

print("✅ All libraries imported successfully!")
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"💻 Device: {device}\n")

# CELL 4: Skills Database  (unchanged from jrv3)
# ============================================================================
SKILLS_DATABASE = [
    # Programming Languages
    'Python', 'Java', 'JavaScript', 'TypeScript', 'C++', 'C#', 'C', 'PHP',
    'Ruby', 'Swift', 'Kotlin', 'Go', 'Rust', 'Scala', 'R', 'MATLAB',
    'Perl', 'Bash', 'Shell', 'PowerShell', 'Lua', 'Julia', 'Haskell',
    'Elixir', 'Erlang', 'Clojure', 'F#', 'Dart', 'Groovy', 'COBOL',
    'Fortran', 'Assembly', 'Objective-C', 'VBA', 'SAS', 'Stata',
    # Web Frontend
    'HTML', 'CSS', 'React', 'Angular', 'Vue.js', 'jQuery', 'Bootstrap',
    'Tailwind CSS', 'SASS', 'LESS', 'Redux', 'Next.js', 'Nuxt.js',
    'Svelte', 'Gatsby', 'Webpack', 'Vite', 'Babel', 'Three.js',
    'WebAssembly', 'PWA', 'Storybook', 'Figma', 'Adobe XD',
    # Web Backend
    'Node.js', 'Express.js', 'Django', 'Flask', 'FastAPI', 'Spring Boot',
    'ASP.NET', 'Ruby on Rails', 'Laravel', 'NestJS', 'Gin', 'Echo',
    'Phoenix', 'Fiber', 'Actix', 'Hapi.js', 'Koa.js', 'Strapi',
    'GraphQL', 'REST API', 'gRPC', 'WebSocket', 'Microservices',
    # Databases
    'MySQL', 'PostgreSQL', 'MongoDB', 'Redis', 'Oracle', 'SQLite',
    'Cassandra', 'DynamoDB', 'Elasticsearch', 'Neo4j', 'MariaDB',
    'CouchDB', 'InfluxDB', 'TimescaleDB', 'Firestore', 'Supabase',
    'SQL', 'NoSQL', 'PL/SQL', 'T-SQL',
    # Data Science & ML
    'TensorFlow', 'PyTorch', 'Keras', 'Scikit-learn', 'Pandas', 'NumPy',
    'Matplotlib', 'Seaborn', 'OpenCV', 'NLTK', 'SpaCy', 'Transformers',
    'Machine Learning', 'Deep Learning', 'Neural Networks', 'NLP',
    'Computer Vision', 'Data Analysis', 'Statistical Analysis',
    'Reinforcement Learning', 'Generative AI', 'LLM', 'RAG',
    'Time Series Analysis', 'Anomaly Detection', 'Recommendation Systems',
    'A/B Testing', 'Hypothesis Testing', 'Regression Analysis',
    'Classification', 'Clustering', 'Dimensionality Reduction',
    'Feature Engineering', 'Model Deployment', 'Model Evaluation',
    'XGBoost', 'LightGBM', 'CatBoost', 'Random Forest',
    # Big Data & Data Engineering
    'Spark', 'Hadoop', 'Kafka', 'Airflow', 'Databricks', 'Hive',
    'Flink', 'Presto', 'Trino', 'dbt', 'Fivetran', 'Stitch',
    'Apache Beam', 'Apache NiFi', 'Delta Lake', 'Iceberg',
    'ETL', 'ELT', 'Data Warehousing', 'Data Pipeline', 'Data Modeling',
    'Redshift', 'BigQuery', 'Snowflake', 'Looker', 'Dataflow',
    # Cloud
    'AWS', 'Azure', 'GCP', 'Heroku', 'DigitalOcean', 'Firebase',
    'Cloudflare', 'Vercel', 'Netlify',
    'AWS Lambda', 'AWS EC2', 'AWS S3', 'AWS RDS', 'AWS EKS',
    'Azure DevOps', 'Azure Functions', 'Google Cloud Run',
    # DevOps
    'Docker', 'Kubernetes', 'Jenkins', 'Git', 'GitHub', 'GitLab',
    'CI/CD', 'Terraform', 'Ansible', 'Linux', 'Unix', 'Nginx',
    'Prometheus', 'Grafana', 'ELK Stack', 'Datadog', 'New Relic',
    'SonarQube', 'ArgoCD', 'Helm', 'Istio', 'Consul', 'Vault',
    'GitHub Actions', 'CircleCI', 'Travis CI', 'Bitbucket',
    # Mobile
    'Android', 'iOS', 'React Native', 'Flutter', 'Xamarin', 'Ionic',
    'Swift UI', 'Jetpack Compose', 'Expo', 'Capacitor',
    # MLOps & AI
    'MLflow', 'Kubeflow', 'SageMaker', 'Vertex AI', 'Ray',
    'HuggingFace', 'LangChain', 'LlamaIndex', 'Weights & Biases',
    'DVC', 'BentoML', 'TorchServe', 'TFServing',
    'OpenAI API', 'Anthropic API', 'Cohere', 'Pinecone', 'Weaviate',
    'ChromaDB', 'FAISS', 'Qdrant',
    # BI & Viz
    'Tableau', 'Power BI', 'Metabase', 'Superset', 'D3.js', 'Plotly',
    'Dash', 'Kibana', 'Google Data Studio', 'Qlik',
    # Security
    'Cybersecurity', 'Penetration Testing', 'Ethical Hacking',
    'Network Security', 'Firewall', 'VPN', 'SIEM', 'SOC',
    'OWASP', 'SSL/TLS', 'IAM', 'OAuth', 'JWT', 'Encryption',
    'Wireshark', 'Metasploit', 'Burp Suite', 'Nmap', 'Kali Linux',
    'ISO 27001', 'NIST', 'SOC 2', 'Zero Trust',
    # Testing
    'Selenium', 'Cypress', 'Jest', 'Mocha', 'Pytest', 'JUnit',
    'Playwright', 'TestNG', 'Appium', 'Postman',
    'Unit Testing', 'Integration Testing', 'Load Testing', 'QA',
    # Project Tools
    'Agile', 'Scrum', 'Kanban', 'JIRA', 'Confluence', 'Notion',
    'Slack', 'Trello', 'Asana', 'Monday.com', 'ClickUp',
    # Design
    'Figma', 'Adobe XD', 'Sketch', 'InVision',
    'UI Design', 'UX Design', 'Wireframing', 'Prototyping',
    'User Research', 'Usability Testing', 'Design Systems',
    'Adobe Photoshop', 'Adobe Illustrator', 'Canva',
    # Blockchain
    'Blockchain', 'Solidity', 'Ethereum', 'Web3.js', 'Hardhat',
    'Smart Contracts', 'DeFi', 'NFT', 'IPFS', 'Polygon', 'Solana',
    # Game Dev
    'Unity', 'Unreal Engine', 'Godot', 'Game Design', 'Level Design',
    '3D Modeling', 'Blender',
    # Embedded
    'Embedded Systems', 'Arduino', 'Raspberry Pi', 'FPGA',
    'VHDL', 'Verilog', 'IoT', 'RTOS', 'Microcontrollers',
    'PLC', 'SCADA', 'Industrial Automation',
    # Finance
    'Excel', 'Microsoft Excel', 'Advanced Excel', 'Tally', 'Tally Prime',
    'QuickBooks', 'Zoho Books', 'SAP', 'SAP FICO', 'Oracle Financials',
    'VLOOKUP', 'Pivot Tables', 'Power Query', 'Macros', 'VBA',
    'Financial Analysis', 'Financial Modeling', 'Financial Reporting',
    'Accounting', 'Bookkeeping', 'Auditing', 'Internal Audit',
    'Taxation', 'GST', 'Income Tax', 'TDS',
    'Cost Accounting', 'Management Accounting', 'Budgeting', 'Forecasting',
    'Investment Analysis', 'Equity Research', 'Portfolio Management',
    'Risk Management', 'Credit Analysis', 'Derivatives',
    'Fundamental Analysis', 'Technical Analysis', 'Valuation',
    'Investment Banking', 'Corporate Finance', 'Treasury Management',
    'IFRS', 'GAAP', 'CFA', 'CA', 'CPA', 'ACCA',
    'Bloomberg Terminal', 'Reuters Eikon',
    # Marketing & Sales
    'Digital Marketing', 'SEO', 'SEM', 'Google Ads', 'Facebook Ads',
    'Content Marketing', 'Email Marketing', 'Social Media Marketing',
    'Brand Management', 'CRM', 'Salesforce', 'HubSpot',
    'Lead Generation', 'Sales', 'B2B Sales', 'B2C Sales',
    'Business Development', 'Copywriting', 'Content Writing',
    'Google Analytics', 'Marketing Automation', 'Mailchimp', 'Marketo',
    'E-commerce', 'Shopify', 'WooCommerce', 'Amazon FBA',
    # HR
    'Human Resources', 'HR', 'Recruitment', 'Talent Acquisition',
    'Payroll', 'HRMS', 'HRIS', 'Workday', 'BambooHR', 'Darwinbox',
    'Performance Management', 'KPI', 'OKR', 'Employee Engagement',
    'Training & Development', 'L&D', 'Compensation & Benefits',
    'HR Analytics', 'Organizational Development', 'Labor Law',
    # Operations
    'Operations Management', 'Supply Chain', 'Logistics', 'Procurement',
    'Vendor Management', 'Inventory Management', 'ERP',
    'Warehouse Management', 'Quality Control', 'Quality Assurance',
    'Six Sigma', 'Lean', 'ISO 9001', 'SAP SCM',
    # PM
    'Project Management', 'Product Management', 'Program Management',
    'PMP', 'Prince2', 'PMI', 'Stakeholder Management',
    'Business Analysis', 'Requirements Gathering', 'Product Roadmap',
    # Healthcare
    'Clinical Research', 'Clinical Trials', 'GCP', 'Pharmacovigilance',
    'Regulatory Affairs', 'FDA', 'Medical Writing', 'Biostatistics',
    'Healthcare Management', 'EMR', 'EHR', 'HL7', 'FHIR',
    'Medical Coding', 'ICD-10', 'MBBS', 'BPharm', 'MPharm',
    # Education
    'Teaching', 'Curriculum Development', 'Instructional Design',
    'E-Learning', 'LMS', 'Moodle', 'Academic Research',
    # Legal
    'Legal Research', 'Contract Drafting', 'Corporate Law',
    'Intellectual Property', 'GDPR', 'Data Privacy', 'Regulatory Compliance',
    'Arbitration', 'Mediation', 'LLB', 'LLM',
    # Engineering (non-software)
    'AutoCAD', 'SolidWorks', 'CATIA', 'ANSYS', 'MATLAB', 'ETABS',
    'Mechanical Engineering', 'Civil Engineering', 'FEA', 'CFD',
    'BIM', 'Revit', 'HVAC', 'Electrical Engineering', 'PLC',
    # Creative
    'Graphic Design', 'Video Production', 'Photography', 'After Effects',
    'Adobe Premiere Pro', 'DaVinci Resolve', 'Journalism', 'Scriptwriting',
    # Other
    'Hotel Management', 'Event Management', 'Travel Management',
    'Personal Training', 'Yoga', 'Nutrition', 'Childcare', 'Fashion Design',
]

# ============================================================================
# CELL 5: Domain Keywords  — used as FALLBACK only (when LLM unavailable/fails)
#          LLM domain suggestions are TRUSTED and used as-is when valid.
#          Keyword scoring activates only when LLM returns nothing usable.
# ============================================================================
DOMAIN_KEYWORDS = {
    'Data Science':       ['machine learning', 'deep learning', 'nlp', 'tensorflow', 'pytorch',
                           'pandas', 'numpy', 'scikit-learn', 'data analysis', 'computer vision',
                           'statistical analysis', 'xgboost', 'lightgbm', 'generative ai', 'llm'],
    'Web Development':    ['react', 'angular', 'vue', 'node.js', 'django', 'flask',
                           'html', 'css', 'javascript', 'typescript', 'next.js', 'svelte'],
    'DevOps':             ['docker', 'kubernetes', 'jenkins', 'ci/cd', 'terraform',
                           'ansible', 'linux', 'aws', 'azure', 'gcp', 'prometheus', 'helm'],
    'Mobile Development': ['android', 'ios', 'flutter', 'react native', 'swift', 'kotlin',
                           'jetpack compose', 'swift ui', 'expo'],
    'Backend':            ['spring boot', 'fastapi', 'microservices', 'rest api', 'grpc',
                           'postgresql', 'mongodb', 'redis', 'kafka', 'rabbitmq'],
    'Data Engineering':   ['spark', 'hadoop', 'airflow', 'dbt', 'databricks', 'kafka',
                           'etl', 'elt', 'data pipeline', 'data warehousing', 'snowflake',
                           'bigquery', 'redshift', 'delta lake'],
    'Cybersecurity':      ['cybersecurity', 'penetration testing', 'ethical hacking',
                           'network security', 'siem', 'soc', 'owasp', 'vulnerability assessment',
                           'incident response', 'kali linux', 'burp suite'],
    'UI/UX Design':       ['figma', 'adobe xd', 'ui design', 'ux design', 'wireframing',
                           'prototyping', 'user research', 'usability testing', 'sketch'],
    'Blockchain':         ['blockchain', 'solidity', 'ethereum', 'web3', 'smart contracts',
                           'defi', 'nft', 'polygon', 'solana'],
    'Game Development':   ['unity', 'unreal engine', 'game design', 'godot',
                           'level design', '3d modeling', 'blender'],
    'Embedded Systems':   ['embedded systems', 'arduino', 'raspberry pi', 'fpga', 'iot',
                           'rtos', 'microcontrollers', 'plc', 'scada', 'vhdl', 'verilog'],
    'Finance':            ['financial analysis', 'financial modeling', 'investment analysis',
                           'equity research', 'portfolio management', 'trading',
                           'tally', 'budgeting', 'forecasting', 'mis reporting', 'cfa',
                           'investment banking', 'corporate finance', 'valuation', 'bloomberg'],
    'Accounting':         ['accounting', 'bookkeeping', 'auditing', 'taxation', 'gst',
                           'tally', 'quickbooks', 'sap fico', 'cost accounting',
                           'financial statements', 'ifrs', 'gaap', 'ca', 'cpa', 'acca'],
    'Marketing':          ['digital marketing', 'seo', 'sem', 'google ads', 'content marketing',
                           'email marketing', 'social media marketing', 'brand management',
                           'performance marketing', 'google analytics', 'marketing automation'],
    'Sales':              ['sales', 'lead generation', 'crm', 'salesforce', 'hubspot',
                           'b2b sales', 'b2c sales', 'account management', 'business development'],
    'HR':                 ['human resources', 'recruitment', 'talent acquisition', 'payroll',
                           'hrms', 'workday', 'performance management', 'l&d', 'hr analytics'],
    'Operations':         ['operations management', 'supply chain', 'logistics', 'procurement',
                           'vendor management', 'inventory management', 'erp', 'six sigma',
                           'lean', 'iso 9001', 'demand planning'],
    'Project Management': ['project management', 'pmp', 'agile', 'scrum', 'kanban',
                           'stakeholder management', 'risk management', 'program management',
                           'safe', 'prince2'],
    'Product Management': ['product management', 'product roadmap', 'product strategy',
                           'backlog grooming', 'sprint planning', 'okr', 'go-to-market'],
    'Consulting':         ['management consulting', 'strategy consulting', 'business strategy',
                           'digital transformation', 'process improvement', 'swot analysis',
                           'competitive intelligence', 'business case'],
    'Business Analysis':  ['business analysis', 'requirements gathering', 'brd', 'frd',
                           'market research', 'data analysis', 'process mapping'],
    'Legal':              ['legal research', 'contract drafting', 'corporate law', 'litigation',
                           'intellectual property', 'gdpr', 'compliance', 'arbitration', 'llb'],
    'Healthcare':         ['clinical research', 'pharmacovigilance', 'regulatory affairs',
                           'medical writing', 'biostatistics', 'ehr', 'fhir', 'medical coding'],
    'Education':          ['teaching', 'curriculum development', 'instructional design',
                           'e-learning', 'academic research', 'lms', 'thesis writing'],
    'Engineering':        ['autocad', 'solidworks', 'catia', 'ansys', 'mechanical engineering',
                           'civil engineering', 'fea', 'cfd', 'bim', 'revit', 'hvac'],
    'Creative':           ['graphic design', 'video production', 'photography', 'figma',
                           'adobe photoshop', 'illustrator', 'motion graphics', 'after effects',
                           'content writing', 'copywriting', 'journalism'],
    'Hospitality':        ['hotel management', 'front office', 'revenue management',
                           'guest relations', 'event planning', 'travel management', 'amadeus'],
    'Fitness & Wellness': ['personal training', 'fitness training', 'group fitness',
                           'nutrition', 'diet planning', 'weight loss', 'yoga', 'pilates',
                           'kinesiology', 'cpr', 'ace certification', 'nasm', 'wellness coaching'],
    'Media & Film':       ['video production', 'video editing', 'adobe premiere pro',
                           'davinci resolve', 'after effects', 'cinematography',
                           'scriptwriting', 'audio editing', 'content creation', 'podcast production'],
    'Fashion':            ['fashion design', 'pattern making', 'fabric selection',
                           'sketching', 'merchandising', 'garment construction', 'visual merchandising'],
    'Nutrition':          ['nutritional counseling', 'dietary assessment', 'meal planning',
                           'food science', 'clinical nutrition', 'dietetics', 'registered dietitian'],
    'Account Management': ['account management', 'key account management', 'global accounts',
                           'client relationship management', 'customer success', 'upselling'],
}

VALID_DOMAINS = set(DOMAIN_KEYWORDS.keys())

# ============================================================================
# CELL 6: Groq LLM Client
# ============================================================================

class GroqLLMClient:
    """
    Wraps the Groq SDK for structured LLM calls used in resume parsing
    and domain / job-title detection.

    Design principles:
      1. Prompt asks the model to return JSON only.
      2. Every LLM call is followed by a domain-keyword validation pass
         that cross-checks the model's domain claims against DOMAIN_KEYWORDS.
      3. The domain keyword set is a fallback only — it fires when the LLM
         returns no usable domain (API failure or unknown label). LLM domain
         suggestions are trusted and used in their original order.
      4. If the API call itself fails, keyword scoring is used directly (fallback).
    """

    def __init__(self, api_key: str, model: str = GROQ_MODEL):
        self.client = Groq(api_key=api_key)
        self.model  = model
        self._available = True  # set False on repeated auth failures

    # ── Low-level call ────────────────────────────────────────────────────────
    def _call(self, system_prompt: str, user_prompt: str,
              max_tokens: int = 1024, temperature: float = 0.1) -> str | None:
        """Call Groq and return raw text response, or None on error."""
        if not self._available:
            return None
        try:
            resp = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user",   "content": user_prompt},
                ],
                max_tokens=max_tokens,
                temperature=temperature,
            )
            return resp.choices[0].message.content.strip()
        except Exception as e:
            print(f"   ⚠️  Groq API error: {e}")
            return None

    # ── JSON extraction helper ────────────────────────────────────────────────
    @staticmethod
    def _parse_json(text: str) -> dict | list | None:
        """Extract JSON from model output (strips markdown fences if present)."""
        if not text:
            return None
        text = re.sub(r'^```(?:json)?\s*', '', text, flags=re.I)
        text = re.sub(r'\s*```$', '', text)
        try:
            return json.loads(text)
        except json.JSONDecodeError:
            # Try extracting first {...} or [...] block
            m = re.search(r'(\{.*\}|\[.*\])', text, re.S)
            if m:
                try:
                    return json.loads(m.group(1))
                except Exception:
                    pass
        return None

    # ── Domain validation against DOMAIN_KEYWORDS ────────────────────────────
    @staticmethod
    def _keyword_score_domains(skills: list[str], top_n: int = 3) -> list[tuple[str, int]]:
        """Score domains by keyword overlap — the ground-truth fallback."""
        sl = [s.lower() for s in skills]
        scores = {
            d: sum(1 for kw in kws if any(kw in s for s in sl))
            for d, kws in DOMAIN_KEYWORDS.items()
        }
        ranked = sorted(scores.items(), key=lambda x: x[1], reverse=True)
        top = [(d, sc) for d, sc in ranked if sc > 0][:top_n]
        return top if top else [('Software Engineer', 0)]

    def validate_domains(self, llm_domains: list[str], skills: list[str]) -> list[tuple[str, int]]:
        """
        Accept LLM domain suggestions as the primary source of truth.

        Rules (LLM-first, keyword-scoring is fallback only):
          1. A domain is accepted as long as it exists in VALID_DOMAINS
             (case-insensitive match). The LLM's ordering is preserved —
             we do NOT re-rank by keyword score.
          2. A domain that cannot be matched to any VALID_DOMAINS entry is
             dropped (the LLM invented a label not in our job-search taxonomy).
          3. The keyword score is informational only (used for the explain
             printout). It does NOT gate acceptance or change ordering.
          4. Keyword fallback fires ONLY when LLM returns zero valid domains
             (API down, parse failure, or every suggestion was unknown label).

        Examples:
          • LLM says ["Data Science", "Backend"] → both accepted as-is, in that order,
            even if resume has zero pandas/sklearn (LLM read context keywords can't).
          • LLM says ["QuantumComputing"] → dropped (not in taxonomy)
            → keyword fallback activates.
          • LLM API fails → keyword scoring takes over for all domains.
        """
        sl       = [s.lower() for s in skills]
        accepted = []
        dropped  = []

        for domain in llm_domains:
            domain = domain.strip()
            if not domain:
                continue

            # Exact match first, then case-insensitive
            if domain in VALID_DOMAINS:
                canonical = domain
            else:
                canonical = next(
                    (d for d in VALID_DOMAINS if d.lower() == domain.lower()), None
                )

            if canonical is None:
                dropped.append(domain)
                continue

            # Attach keyword score for transparency / explain printout only
            kws   = DOMAIN_KEYWORDS[canonical]
            score = sum(1 for kw in kws if any(kw in s for s in sl))
            accepted.append((canonical, score))

        if dropped:
            print(f"   ℹ️  LLM domain(s) not in taxonomy (dropped): {', '.join(dropped)}")

        if accepted:
            # Preserve LLM ordering — do NOT sort by keyword score
            seen   = set()
            unique = []
            for d, sc in accepted:
                if d not in seen:
                    seen.add(d)
                    unique.append((d, sc))
            print(f"   ✅ Using LLM domains (trusted): {[d for d, _ in unique[:3]]}")
            return unique[:3]

        # ── Fallback: LLM gave nothing usable ────────────────────────────────
        print("   ⚠️  No valid LLM domains — activating keyword-scoring fallback")
        return self._keyword_score_domains(skills)

    # ── Resume parsing via LLM ────────────────────────────────────────────────
    def parse_resume_llm(self, resume_text: str) -> dict | None:
        """
        Use Groq to extract structured information from raw resume text.

        Returns a dict with keys:
          skills           : list[str]
          experience_years : float
          education_level  : str
          domains_raw      : list[str]   ← raw LLM domain suggestions (pre-validation)
          job_title        : str
        Returns None if API fails (caller uses regex fallback).
        """
        system = (
            "You are an expert resume-parsing and career-classification engine. "
            "Your job is to read the resume text and extract: skills, total experience, "
            "education, the best-matching job domain(s), and the most fitting job title. "
            "Return ONLY a valid JSON object — no commentary, preamble, or markdown fences. "
            "For skills: include every tool, language, framework, platform, and methodology "
            "explicitly or clearly implied in the resume. "
            "For domain and job_title: use your full understanding of the resume context, "
            "not just keyword matching."
        )

        valid_domains_str = ", ".join(sorted(VALID_DOMAINS))

        user = f"""Parse the following resume and return a JSON object with exactly these keys:

{{
  "skills": ["list of technical and professional skills mentioned"],
  "experience_years": <float, total years of professional experience>,
  "education_level": "<highest qualification e.g. B.Tech in Computer Science, MBA, MCA>",
  "domains": ["top 1-3 job domains that best match this candidate, choose ONLY from: {valid_domains_str}"],
  "job_title": "<single most appropriate job title for this candidate>"
}}

Rules:
- skills: include tools, languages, frameworks, soft skills — only those explicitly in the resume.
- experience_years: sum all non-overlapping work periods in years (float, e.g. 2.5). Return 0 if fresher.
- education_level: use the exact degree name from the resume.
- domains: MUST be chosen from the provided list only. Do NOT invent new domains.
- job_title: be specific (e.g. "Senior Data Scientist" not just "Engineer").

RESUME TEXT:
\"\"\"
{resume_text[:6000]}
\"\"\"
"""

        raw = self._call(system, user, max_tokens=800)
        if not raw:
            return None

        parsed = self._parse_json(raw)
        if not isinstance(parsed, dict):
            print("   ⚠️  LLM returned non-dict JSON — falling back")
            return None

        # Normalise types
        result = {
            'skills':           parsed.get('skills', []) or [],
            'experience_years': float(parsed.get('experience_years', 0) or 0),
            'education_level':  str(parsed.get('education_level', 'B.Tech in Computer Science')),
            'domains_raw':      parsed.get('domains', []) or [],
            'job_title':        str(parsed.get('job_title', '')),
        }

        if not isinstance(result['skills'], list):
            result['skills'] = []
        if not isinstance(result['domains_raw'], list):
            result['domains_raw'] = []

        return result

    # ── NOTE: job title is extracted inside parse_resume_llm() in the same ─────
    # single LLM call that handles skills / experience / education / domains.
    # No separate LLM call is needed for title detection.
    # The title is passed through llm_result['job_title'] → user_profile['job_title']
    # → JobProcessor.scrape_jobs(llm_job_title=...) as the first search term.

    def extract_job_skills_llm(self, job_descriptions: list[dict]) -> dict[str, list[str]]:
        """
        Use Groq LLM to batch-extract skills/requirements from job descriptions.
        Called only for non-tech jobs where SKILLS_DATABASE regex fails.

        Returns a dict: { job_id -> [skill1, skill2, ...] }
        Processes in batches of 5 to stay within token limits.
        """
        if not self._available:
            return {}

        system = (
            "You are an expert job description analyser. "
            "For each job given, extract the key skills, qualifications, tools, "
            "certifications, and domain knowledge required. "
            "Return ONLY a valid JSON object — no commentary, no markdown fences. "
            "Be comprehensive: include soft skills, domain terms, certifications, "
            "equipment, methodologies — anything a candidate needs for this role."
        )

        results = {}
        # Process in batches of 5 to avoid token limit
        batch_size = 5
        items = list(job_descriptions)

        for batch_start in range(0, len(items), batch_size):
            batch = items[batch_start: batch_start + batch_size]
            jobs_block = ""
            for entry in batch:
                jid  = entry['job_id']
                desc = entry['description'][:800]   # cap per-job tokens
                jobs_block += f'\nJOB_ID: {jid}\nDESCRIPTION:\n"""\n{desc}\n"""\n'

            user = f"""For each job below, extract required skills and qualifications.
Return a JSON object where each key is the JOB_ID and the value is a list of skills.

Example format:
{{
  "job_0": ["Patient Care", "Surgery", "MBBS", "Laparoscopy"],
  "job_1": ["Financial Analysis", "Excel", "CFA", "Valuation"]
}}

{jobs_block}
"""
            raw = self._call(system, user, max_tokens=1200, temperature=0.0)
            if not raw:
                continue
            parsed = self._parse_json(raw)
            if isinstance(parsed, dict):
                for jid, skills in parsed.items():
                    if isinstance(skills, list):
                        results[jid] = [str(s).strip() for s in skills if s]

        return results

    # ── Batch LLM job relevance scoring ──────────────────────────────────────
    def score_jobs_with_llm(self, user_profile: dict, jobs: list[dict],
                             batch_size: int = 10) -> dict[str, float]:
        """
        Ask Groq to rate how well each job matches the candidate.
        Works for ANY domain — tech or non-tech — because Groq understands
        context, not just keywords.

        Returns a dict of {job_id: llm_score (0.0–1.0)}.
        Falls back gracefully to empty dict on API failure (caller uses 0.5 neutral).

        Strategy:
          • Jobs are sent in batches of `batch_size` to stay within token limits.
          • Groq returns a JSON array of {job_id, score, reason}.
          • score is normalised to [0, 1].
        """
        if not self._available:
            return {}

        llm_scores = {}
        candidate_summary = (
            f"Job Title: {user_profile.get('job_title', 'Not specified')}\n"
            f"Domain: {user_profile.get('domain', 'Not specified')}\n"
            f"Experience: {user_profile.get('experience_years', 0)} years\n"
            f"Education: {user_profile.get('education_level', 'Not specified')}\n"
            f"Key Skills: {', '.join(user_profile.get('skills', [])[:20])}\n"
            f"Resume Summary (first 800 chars):\n{user_profile.get('resume_text', '')[:800]}"
        )

        system = (
            "You are an expert recruitment AI. Given a candidate profile and a list of job postings, "
            "rate how relevant each job is for this,"
        )

# ============================================================================
# CELL 7: PDF / DOCX Text Utilities  (unchanged)
# ============================================================================
def normalize_pdf_text(text):
    import unicodedata
    text = unicodedata.normalize('NFKC', text)
    text = re.sub(r'[ \t]+', ' ', text)
    text = re.sub(r'\n{3,}', '\n\n', text)
    return text.strip()

# CELL 8: ResumeParser — Groq LLM primary, keyword regex fallback
# ============================================================================

class ResumeParser:
    """
    Two-pass parser:
      PASS 1 (LLM)  — Groq extracts skills, experience, education, domains, title.
                      Domain suggestions are validated against DOMAIN_KEYWORDS.
      PASS 2 (regex) — Used when LLM is unavailable or returned empty/invalid data.
                      Identical to jrv3 keyword-matching logic.

    The domain keyword set is NEVER bypassed — it acts as a hard validator on
    LLM output, ensuring the system cannot act on a claimed false domain.
    """

    SKILL_ALIASES = {
        "sklearn": "Scikit-learn", "scikit learn": "Scikit-learn",
        "nodejs": "Node.js", "node js": "Node.js",
        "reactjs": "React.js", "react js": "React.js",
        "vuejs": "Vue.js", "nextjs": "Next.js",
        "golang": "Go", "k8s": "Kubernetes",
        "tf": "TensorFlow", "postgres": "PostgreSQL",
        "amazon web services": "AWS", "google cloud platform": "GCP",
        "restful api": "REST API", "huggingface": "HuggingFace",
        "hugging face": "HuggingFace", "powerbi": "Power BI",
    }

    STRICT_SINGLE_LETTER = {'R', 'C', 'Go'}

    EDUCATION_MAP = [
        (['m.tech in ai', 'm.tech ai', 'artificial intelligence'], 'M.Tech in Artificial Intelligence'),
        (['m.tech in data', 'm.sc in data', 'msc data'],           'M.Sc in Data Science'),
        (['m.tech', 'm.e.', 'me in'],                              'M.Tech in Computer Science'),
        (['mca', 'master of computer'],                            'MCA (Master of Computer Applications)'),
        (['mba'],                                                   'MBA'),
        (['bca', 'bachelor of computer'],                          'BCA (Bachelor of Computer Applications)'),
        (['b.des', 'bdes', 'design'],                              'B.Des in Design'),
        (['b.tech in mechanical', 'b.e. in mechanical'],           'B.Tech in Mechanical Engineering'),
        (['b.tech in electronics', 'ece', 'electronics'],          'B.Tech in Electronics and Communication'),
        (['b.e. in information', 'b.e in information'],            'B.E. in Information Technology'),
        (['b.sc', 'bsc', 'b.s.'],                                  'B.Sc in Computer Science'),
        (['b.com', 'bcom'],                                        'B.Com with Digital Marketing Certification'),
        (['b.tech', 'b.e.'],                                       'B.Tech in Computer Science'),
        (['ph.d', 'phd', 'doctorate'],                             'M.Tech in Computer Science'),
    ]

    # ── PDF / DOCX extraction ─────────────────────────────────────────────────
    def extract_text_from_pdf(self, path):
        chunks = []
        with pdfplumber.open(path) as pdf:
            for page in pdf.pages:
                t = self._page_text(page)
                if t:
                    chunks.append(t)
        return normalize_pdf_text("\n\n".join(chunks))

    def _page_text(self, page):
        words = page.extract_words(x_tolerance=2, y_tolerance=2) or []
        if words:
            s = self._from_words(page.width, words)
            if s and len(s.strip()) >= 30:
                return s
        return page.extract_text(layout=True) or page.extract_text() or ""

    def _from_words(self, pw, words):
        cs = [(w["x0"] + w["x1"]) / 2 for w in words]
        left  = sum(1 for c in cs if c < pw * 0.45)
        right = sum(1 for c in cs if c > pw * 0.55)
        mid   = len(cs) - left - right
        if (left / len(cs) > 0.22 and right / len(cs) > 0.22 and mid / len(cs) < 0.25):
            sx = pw * 0.5
            return "\n".join(
                self._lines([w for w in words if w["x1"] <= sx + 6]) + [""] +
                self._lines([w for w in words if w["x0"] >= sx - 6])
            ).strip()
        return "\n".join(self._lines(words)).strip()

    def _lines(self, words, y_tol=2.5):
        if not words: return []
        rows = []
        for word in sorted(words, key=lambda w: (round(w["top"], 1), w["x0"])):
            placed = False
            for row in rows:
                if abs(row["top"] - word["top"]) <= y_tol:
                    row["words"].append(word)
                    row["top"] = (row["top"] + word["top"]) / 2
                    placed = True; break
            if not placed:
                rows.append({"top": word["top"], "words": [word]})
        return [" ".join(w["text"] for w in sorted(r["words"], key=lambda w: w["x0"])).strip()
                for r in sorted(rows, key=lambda r: r["top"])
                if " ".join(w["text"] for w in r["words"]).strip()]

    def extract_text_from_docx(self, path):
        doc = docx.Document(path)
        parts = [p.text.strip() for p in doc.paragraphs if p.text.strip()]
        for tbl in doc.tables:
            for row in tbl.rows:
                cells = [c.text.strip() for c in row.cells if c.text.strip()]
                if cells: parts.append(" | ".join(cells))
        return "\n".join(parts)

    # ── Regex-based extractors (PASS 2 fallback) ──────────────────────────────
    def _regex_extract_skills(self, text: str) -> list[str]:
        tl = ' ' + text.lower() + ' '
        found = set()
        for skill in SKILLS_DATABASE:
            sl = skill.lower()
            if skill in self.STRICT_SINGLE_LETTER:
                pat = r'(?<![a-zA-Z0-9])' + re.escape(sl) + r'(?![a-zA-Z0-9])'
                skill_context = re.search(
                    r'(skills?|technologies|tech stack|languages?|proficient|'
                    r'expertise|tools?|frameworks?)[^\n]{0,200}' + pat, tl, re.I)
                direct = re.search(
                    r'(?:^|[\s,•|/])' + re.escape(sl) + r'(?:[\s,•|/\n]|$)', tl)
                if not (skill_context or direct):
                    continue
            elif re.search(r'[^a-z0-9]', sl):
                pat = r'(?<![a-z0-9])' + re.escape(sl) + r'(?![a-z0-9])'
            else:
                pat = r'\b' + re.escape(sl) + r'\b'
            if re.search(pat, tl):
                found.add(skill)
        for alias, canon in self.SKILL_ALIASES.items():
            if re.search(r'(?<![a-z0-9])' + re.escape(alias) + r'(?![a-z0-9])', tl):
                found.add(canon)
        return sorted(found)

    def _regex_extract_experience(self, text: str) -> float:
        tl = text.lower()
        MONTH_MAP = {
            'jan': 1, 'january': 1, 'feb': 2, 'february': 2, 'mar': 3, 'march': 3,
            'apr': 4, 'april': 4, 'may': 5, 'jun': 6, 'june': 6, 'jul': 7, 'july': 7,
            'aug': 8, 'august': 8, 'sep': 9, 'september': 9, 'oct': 10, 'october': 10,
            'nov': 11, 'november': 11, 'dec': 12, 'december': 12,
        }
        MP = (r'(january|february|march|april|may|june|july|august|september|'
              r'october|november|december|jan|feb|mar|apr|jun|jul|aug|sep|oct|nov|dec)\.?')
        EP = (r'(january|february|march|april|may|june|july|august|september|'
              r'october|november|december|jan|feb|mar|apr|jun|jul|aug|sep|oct|nov|'
              r'dec|present|current)\.?\s*(\d{4})?')
        now = datetime.now()
        ranges = []
        for line in tl.split('\n'):
            line = re.sub(r'(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)(\d{4})',
                          r'\1 \2', line.strip(), flags=re.I)
            m2 = re.search(MP + r'\s*(\d{4})\s*[-\u2013\u2014.to]+\s*' + EP, line, re.I)
            if m2:
                try:
                    sm = MONTH_MAP.get(m2.group(1).replace('.', '').strip(), 1)
                    sy = int(m2.group(2))
                    et = m2.group(3).replace('.', '').strip()
                    eys = m2.group(4)
                    if et in ('present', 'current'): em, ey = now.month, now.year
                    else:
                        em = MONTH_MAP.get(et, 12)
                        ey = int(eys) if eys else now.year
                    s, e = datetime(sy, sm, 1), datetime(ey, em, 1)
                    if e >= s: ranges.append((s, e))
                except Exception:
                    continue
        from datetime import timedelta
        if not ranges: return 0.0
        ranges.sort(key=lambda x: x[0])
        merged = [ranges[0]]
        for cs, ce in ranges[1:]:
            ls, le = merged[-1]
            if cs <= le + timedelta(days=1): merged[-1] = (ls, max(le, ce))
            else: merged.append((cs, ce))
        return round(sum((e - s).days for s, e in merged) / 365.25, 1)

    def _regex_extract_education(self, text: str) -> str:
        t = text.lower()
        for keywords, label in self.EDUCATION_MAP:
            if any(k in t for k in keywords):
                return label
        return 'B.Tech in Computer Science'

    # ── Domain detection (keyword scoring — used in PASS 2 and validation) ───
    def detect_domains_keyword(self, skills: list[str], top_n: int = 3) -> list[tuple[str, int]]:
        sl = [s.lower() for s in skills]
        scores = {d: sum(1 for kw in kws if any(kw in s for s in sl))
                  for d, kws in DOMAIN_KEYWORDS.items()}
        ranked = sorted(scores.items(), key=lambda x: x[1], reverse=True)
        top = [(d, s) for d, s in ranked if s > 0][:top_n]
        return top if top else [('Software Engineer', 0)]

    # ── LLM skill deduplication against SKILLS_DATABASE ──────────────────────
    @staticmethod
    def _normalize_llm_skills(llm_skills: list[str]) -> list[str]:
        """
        Map LLM-returned skill strings to canonical SKILLS_DATABASE entries
        where possible; keep the rest as-is.
        """
        db_lower = {s.lower(): s for s in SKILLS_DATABASE}
        result = []
        seen   = set()
        for s in llm_skills:
            s = s.strip()
            if not s or s.lower() in seen:
                continue
            seen.add(s.lower())
            canonical = db_lower.get(s.lower(), s)
            result.append(canonical)
        return sorted(result)

    # ── Explanation printout ──────────────────────────────────────────────────
    def explain_domain_detection(self, skills: list[str], domains: list[tuple[str, int]],
                                 source: str = "keyword"):
        sl = [s.lower() for s in skills]
        print("\n" + "=" * 60)
        print(f"🧠 DOMAIN DETECTION  [source: {source.upper()}]")
        print("=" * 60)
        # score=0 is only a failure signal for pure keyword paths;
        # LLM-sourced domains are trusted regardless of keyword score
        llm_sourced = "groq" in source.lower()
        if not domains:
            print("⚠️  No domains detected — defaulting to Software Engineer")
            return
        if not llm_sourced and domains[0][1] == 0:
            print("⚠️  No keyword match found — defaulting to Software Engineer")
            return
        for rank, (domain, score) in enumerate(domains, 1):
            kws     = DOMAIN_KEYWORDS.get(domain, [])
            matched = [sk for sk in skills if any(kw in sk.lower() or sk.lower() in kw
                                                   for kw in kws)]
            bar     = "█" * min(score, 15) + "░" * (15 - min(score, 15))
            label   = "🥇 PRIMARY" if rank == 1 else f"🥈 #{rank}"
            print(f"\n  {label}  {domain}")
            print(f"  Score : [{bar}] {score} skill(s) matched")
            if matched:
                skill_str = ", ".join(matched)
                print(f"  Skills: {skill_str[:120]}")

        other_scores = {
            d: sum(1 for kw in kws if any(kw in s for s in sl))
            for d, kws in DOMAIN_KEYWORDS.items()
        }
        other = sorted(
            [(d, sc) for d, sc in other_scores.items()
             if sc > 0 and d not in [dom for dom, _ in domains]],
            key=lambda x: x[1], reverse=True
        )
        if other:
            print(f"\n  ─── Other detected domains (not searched) ───")
            for d, sc in other[:5]:
                print(f"  • {d:<25} ({sc} skill match{'es' if sc > 1 else ''})")

        print(f"\n  ✅ Job search will cover: {', '.join(d for d, _ in domains)}")
        print("=" * 60)

    # ── Main parse entry point ────────────────────────────────────────────────
    def parse_resume(self, path: str, ftype: str = 'pdf',
                     groq_client: GroqLLMClient | None = None) -> dict:
        print(f"\n📄 Parsing: {os.path.basename(path)}")
        print("=" * 60)

        # ── Extract raw text ──────────────────────────────────────────────────
        if ftype == 'pdf':
            text = self.extract_text_from_pdf(path)
            raw  = ""
            with pdfplumber.open(path) as pdf:
                for page in pdf.pages:
                    t = page.extract_text()
                    if t: raw += t + "\n"
            raw = normalize_pdf_text(raw)
        elif ftype in ('docx', 'doc'):
            text = self.extract_text_from_docx(path)
            raw  = text
        else:
            text = open(path, 'r', encoding='utf-8', errors='ignore').read()
            raw  = text

        if not text or len(text) < 50:
            raise ValueError("Could not extract text from resume")

        llm_success = False
        parse_source = "keyword-regex"   # logging only

        # ════════════════════════════════════════════════════════════════════
        # PASS 1: Groq LLM parsing  (PRIMARY — trusted as-is)
        # ════════════════════════════════════════════════════════════════════
        if groq_client:
            print("\n🤖 PASS 1: Groq LLM parsing (primary)...")
            print(f"   Model : {groq_client.model}")
            print(f"   Tasks : resume parsing + domain detection + job title detection")
            llm_result = groq_client.parse_resume_llm(text)

            if llm_result:
                skills           = self._normalize_llm_skills(llm_result['skills'])
                experience_years = llm_result['experience_years']
                education_level  = llm_result['education_level'] or self._regex_extract_education(text)
                job_title        = llm_result['job_title']
                domains_raw      = llm_result['domains_raw']

                print(f"   ✅ LLM extracted:")
                print(f"      Skills          : {len(skills)} ({', '.join(skills[:6])}{'...' if len(skills) > 6 else ''})")
                print(f"      Experience      : {experience_years} years")
                print(f"      Education       : {education_level}")
                print(f"      Job title       : {job_title}")
                print(f"      Domains (raw)   : {domains_raw}")

                # ── Domain acceptance ─────────────────────────────────────
                # validate_domains trusts LLM ordering; keyword scoring is
                # informational only and fires as fallback when LLM gives nothing.
                print(f"   LLM suggested domains : {domains_raw}")
                domains = groq_client.validate_domains(domains_raw, skills)

                # ── Supplement skills with regex if LLM returned very few ──
                # Domain is NOT re-evaluated after this — LLM domains stand.
                if len(skills) < 5:
                    print("   ℹ️  Few skills from LLM — supplementing with regex (domains unchanged)")
                    regex_skills = self._regex_extract_skills(text)
                    seen = {s.lower() for s in skills}
                    for rs in regex_skills:
                        if rs.lower() not in seen:
                            skills.append(rs)
                            seen.add(rs.lower())

                llm_success  = True
                parse_source = "groq-llm (domain-keyword fallback only)"
            else:
                print("   ⚠️  LLM returned no usable data — activating keyword-regex fallback")

        # ════════════════════════════════════════════════════════════════════
        # PASS 2: Regex / keyword fallback
        # ════════════════════════════════════════════════════════════════════
        if not llm_success:
            print("\n🔧 PASS 2: Regex keyword extraction (fallback)...")
            skills           = self._regex_extract_skills(text)
            experience_years = self._regex_extract_experience(raw)
            education_level  = self._regex_extract_education(text)
            domains          = self.detect_domains_keyword(skills, top_n=3)
            job_title        = ""   # will be filled from DOMAIN_SEARCH_TERMS later
            parse_source     = "keyword-regex"

        # ── Summary ───────────────────────────────────────────────────────────
        domain = domains[0][0]
        print(f"\n✅ RESUME PARSED SUCCESSFULLY  [{parse_source}]")
        print(f"   Skills detected : {len(skills)}")
        print(f"   Experience      : {experience_years} years")
        print(f"   Education       : {education_level}")
        print(f"   Primary domain  : {domain}")
        if job_title:
            print(f"   Job title       : {job_title}")
        if skills:
            print(f"   Top skills      : {', '.join(skills[:10])}")

        self.explain_domain_detection(skills, domains, source=parse_source)

        return {
            'skills':           skills,
            'experience_years': experience_years,
            'education_level':  education_level,
            'domain':           domain,
            'domains':          domains,
            'job_title':        job_title,
            'resume_text':      text,
            'parse_source':     parse_source,
        }

# CELL 9: Job Scraper & Processor  (unchanged from jrv3)
# ============================================================================
class JobProcessor:

    # Domain → best job search term (includes LLM-detected title override)
    DOMAIN_SEARCH_TERMS = {
        'Data Science':       'Data Scientist',
        'Web Development':    'Web Developer',
        'DevOps':             'DevOps Engineer',
        'Mobile Development': 'Mobile App Developer',
        'Backend':            'Backend Developer',
        'Data Engineering':   'Data Engineer',
        'Cybersecurity':      'Cybersecurity Analyst',
        'UI/UX Design':       'UI UX Designer',
        'Blockchain':         'Blockchain Developer',
        'Game Development':   'Game Developer',
        'Embedded Systems':   'Embedded Systems Engineer',
        'Finance':            'Finance Analyst',
        'Accounting':         'Accountant',
        'Marketing':          'Marketing Executive',
        'Sales':              'Sales Executive',
        'HR':                 'HR Executive',
        'Operations':         'Operations Manager',
        'Project Management': 'Project Manager',
        'Product Management': 'Product Manager',
        'Consulting':         'Management Consultant',
        'Business Analysis':  'Business Analyst',
        'Legal':              'Legal Associate',
        'Healthcare':         'Healthcare Professional',
        'Education':          'Teacher',
        'Engineering':        'Mechanical Engineer',
        'Creative':           'Graphic Designer',
        'Hospitality':        'Hotel Management',
        'Fitness & Wellness': 'Personal Trainer',
        'Media & Film':       'Video Editor',
        'Fashion':            'Fashion Designer',
        'Nutrition':          'Nutritionist',
        'Account Management': 'Account Manager',
        'Software Engineer':  'Software Engineer',
    }

    def __init__(self):
        self.skills_db = SKILLS_DATABASE

    def scrape_jobs(self, location="India", results_wanted=100,
                    site_names=None, domains=None, domain='Software Engineer',
                    llm_job_title: str = ""):
        """
        Scrape jobs for all validated domains.
        If an LLM job title is available, prepend it as the first search term.
        """
        if site_names is None:
            site_names = ['indeed', 'linkedin']

        print(f"\n🔍 SCRAPING JOBS")
        print("=" * 60)
        print(f"   Location: {location}  |  Sites: {', '.join(site_names)}")

        search_terms = []

        # If LLM provided a specific job title, use it first (most targeted search)
        if llm_job_title and llm_job_title.strip():
            search_terms.append(llm_job_title.strip())
            print(f"   🤖 LLM job title (primary search): '{llm_job_title.strip()}'")

        if domains:
            for d, _ in domains:
                term = self.DOMAIN_SEARCH_TERMS.get(d, d)
                if term not in search_terms:
                    search_terms.append(term)
        else:
            term = self.DOMAIN_SEARCH_TERMS.get(domain, domain)
            if term not in search_terms:
                search_terms.append(term)

        # ── Broader fallback terms for non-tech domains ───────────────────────
        # Non-tech job titles are often niche; add a broad domain term so we
        # always get enough postings to rank from.
        NON_TECH_BROAD_FALLBACK = {
            'Healthcare':         ['Doctor', 'Physician', 'Medical Officer', 'Surgeon'],
            'HR':                 ['HR Manager', 'Human Resources'],
            'Marketing':          ['Marketing Manager', 'Digital Marketer'],
            'Sales':              ['Sales Manager', 'Business Development'],
            'Finance':            ['Finance Manager', 'Financial Analyst'],
            'Accounting':         ['Accountant', 'CA', 'Finance Executive'],
            'Legal':              ['Lawyer', 'Legal Counsel', 'Advocate'],
            'Education':          ['Teacher', 'Faculty', 'Lecturer', 'Trainer'],
            'Operations':         ['Operations Manager', 'Operations Executive'],
            'Hospitality':        ['Hotel Manager', 'Hospitality Executive'],
            'Creative':           ['Graphic Designer', 'Content Creator'],
            'Fitness & Wellness': ['Fitness Trainer', 'Wellness Coach'],
            'Media & Film':       ['Video Editor', 'Content Producer'],
            'Engineering':        ['Mechanical Engineer', 'Civil Engineer'],
            'Consulting':         ['Management Consultant', 'Business Consultant'],
            'Project Management': ['Project Manager', 'Program Manager'],
            'Product Management': ['Product Manager', 'Product Owner'],
        }
        # Add broad fallback terms if the primary domain has them
        primary_domain = domain if domain else (domains[0][0] if domains else '')
        for fallback_term in NON_TECH_BROAD_FALLBACK.get(primary_domain, []):
            if fallback_term not in search_terms:
                search_terms.append(fallback_term)

        print(f"   Search Terms: {', '.join(search_terms)}")
        per_term = max(50, results_wanted // max(len(search_terms), 1))

        country = 'india' if 'india' in location.lower() else location.split(',')[-1].strip().lower()
        all_dfs = []
        for term in search_terms:
            try:
                print(f"   🔎 Searching: '{term}'...")
                df = scrape_jobs(
                    site_name=site_names,
                    search_term=term,
                    location=location,
                    results_wanted=per_term,
                    hours_old=168,
                    country_indeed=country
                )
                if df is not None and len(df) > 0:
                    all_dfs.append(df)
                    print(f"      → {len(df)} jobs")
            except Exception as e:
                print(f"      ⚠️  '{term}' failed: {e}")

        if not all_dfs:
            print("❌ All scraping attempts failed")
            return []

        combined = pd.concat(all_dfs, ignore_index=True)
        combined = combined.drop_duplicates(subset=['title', 'company'], keep='first')
        print(f"✅ Scraped {len(combined)} unique jobs across {len(search_terms)} term(s)")
        return combined.to_dict('records')

    def extract_skills_from_description(self, description):
        if not description: return []
        text_lower = ' ' + str(description).lower() + ' '
        found = [sk for sk in self.skills_db
                 if re.search(r'\b' + re.escape(sk.lower()) + r'\b', text_lower)]
        return sorted(set(found))

    def extract_required_experience(self, description):
        if not description: return 3
        tl = str(description).lower()
        for pat in [
            r'(\d+)\+?\s*(?:to|\-)\s*(\d+)\s*(?:years?|yrs?)',
            r'(\d+)\+?\s*(?:years?|yrs?)(?:\s+of)?\s+(?:experience|exp)',
        ]:
            m = re.search(pat, tl)
            if m:
                if len(m.groups()) > 1 and m.group(2):
                    return int((int(m.group(1)) + int(m.group(2))) / 2)
                return int(m.group(1))
        if any(t in tl for t in ['entry level', 'junior', 'fresher', 'graduate']): return 0
        if any(t in tl for t in ['senior', 'lead', 'principal', 'staff']):         return 7
        return 3

    def process_jobs(self, jobs_list, is_non_tech: bool = False,
                     groq_client=None):
        print(f"\n🔧 PROCESSING {len(jobs_list)} JOBS")
        print("=" * 60)
        processed = []
        for i, job in enumerate(jobs_list):
            try:
                desc = job.get('description', '')
                if not desc: continue
                # For tech: fast regex against SKILLS_DATABASE (unchanged)
                # For non-tech: start with regex, LLM will enrich later
                skills  = self.extract_skills_from_description(desc)
                req_exp = self.extract_required_experience(desc)
                raw_type = str(job.get('job_type', '') or '').strip().lower()
                if 'part'     in raw_type: jtype = 'Part-time'
                elif 'contract' in raw_type: jtype = 'Contract'
                elif 'intern'   in raw_type: jtype = 'Internship'
                elif 'hybrid'   in raw_type: jtype = 'Hybrid'
                elif 'remote'   in raw_type or 'wfh' in raw_type: jtype = 'Work from Home'
                else: jtype = 'Full-time'
                processed.append({
                    'job_id':              f"job_{i}",
                    'title':               job.get('title', 'Unknown Position'),
                    'company':             job.get('company', 'Unknown Company'),
                    'location':            job.get('location', 'Not specified'),
                    'job_type':            jtype,
                    'description':         str(desc)[:500],
                    'full_description':    str(desc),
                    'skills':              skills,
                    'required_experience': req_exp,
                    'job_url':             job.get('job_url', '#'),
                    'date_posted':         str(job.get('date_posted', 'Recently')),
                })
            except Exception:
                continue

        # ── LLM skill enrichment — runs for ALL domains ───────────────────────
        # Tech:     enrich jobs where regex found <5 skills (misses aliases/new libs)
        # Non-tech: enrich jobs where regex found <3 skills (DB barely covers it)
        # LLM batch-extracts real domain skills from job descriptions and merges them
        # back so BERT and ConvDeepFM see richer, accurate skill vocabulary.
        if groq_client is not None:
            enrich_threshold = 3 if is_non_tech else 5
            to_enrich = [
                {'job_id': j['job_id'], 'description': j['full_description']}
                for j in processed if len(j['skills']) < enrich_threshold
            ]
            if to_enrich:
                print(f"   🤖 LLM enriching {len(to_enrich)} jobs "
                      f"(regex <{enrich_threshold} skills) — {'NON-TECH' if is_non_tech else 'TECH'} mode...")
                llm_skills_map = groq_client.extract_job_skills_llm(to_enrich)
                enriched = 0
                for job in processed:
                    jid = job['job_id']
                    if jid in llm_skills_map:
                        llm_sk = llm_skills_map[jid]
                        existing = set(s.lower() for s in job['skills'])
                        for sk in llm_sk:
                            if sk.lower() not in existing:
                                job['skills'].append(sk)
                                existing.add(sk.lower())
                        enriched += 1
                print(f"   ✅ LLM enriched {enriched} jobs with domain-specific skills")

        print(f"✅ Processed {len(processed)} jobs")
        return processed

# CELL 10: ConvDeepFM Model Architecture — V1 (BERT-based, unchanged)
# ============================================================================
class ConvDeepFM(nn.Module):

    def __init__(self, field_dims, deep_dim, embed_dim=64):
        super().__init__()
        num_fields  = len(field_dims)
        kernel_sizes = [k for k in [2, 3, 4] if k <= num_fields]
        assert kernel_sizes, f"No valid CNN kernels for {num_fields} fields!"
        print(f"  CNN kernels used: {kernel_sizes} (fields={num_fields})")

        self.embedding = nn.Embedding(sum(field_dims), embed_dim)
        self.register_buffer(
            "offsets",
            torch.tensor(np.array((0, *np.cumsum(field_dims)[:-1])), dtype=torch.long)
        )
        self.embed_dropout = nn.Dropout(0.2)
        self.convs = nn.ModuleList([nn.Conv1d(embed_dim, 64, k) for k in kernel_sizes])
        cnn_out_dim = 64 * len(kernel_sizes)
        self.deep_bn = nn.BatchNorm1d(deep_dim)
        self.deep = nn.Sequential(
            nn.Linear(cnn_out_dim + deep_dim, 256), nn.ReLU(), nn.Dropout(0.4),
            nn.Linear(256, 128), nn.ReLU(), nn.Dropout(0.3),
            nn.Linear(128, 1)
        )
        self.fusion = nn.Linear(2, 1)

    def forward(self, x_cat, x_deep):
        x_deep = self.deep_bn(x_deep)
        x_cat  = x_cat + self.offsets
        emb    = self.embed_dropout(self.embedding(x_cat))
        sum_sq = torch.sum(emb, dim=1) ** 2
        sq_sum = torch.sum(emb ** 2, dim=1)
        fm_out = 0.5 * torch.sum(sum_sq - sq_sum, dim=1, keepdim=True)
        x      = emb.permute(0, 2, 1)
        cnn_out = torch.cat([
            torch.max(torch.relu(conv(x)), dim=2)[0] for conv in self.convs
        ], dim=1)
        deep_out = self.deep(torch.cat([cnn_out, x_deep], dim=1))
        return self.fusion(torch.cat([fm_out, deep_out], dim=1)).squeeze(1)

# CELL 11: ConvDeepFM Job Recommender — V1 (unchanged from jrv3)
# ============================================================================
class ConvDeepFMJobRecommender:

    KNOWN_JOB_TYPES = ['Contract', 'Full-time', 'Hybrid', 'Internship', 'Part-time', 'Work from Home']
    KNOWN_LOCATIONS = [
        'Ahmedabad, Gujarat', 'Bangalore, Karnataka', 'Bhubaneswar, Odisha',
        'Chandigarh', 'Chennai, Tamil Nadu', 'Coimbatore, Tamil Nadu',
        'Delhi NCR', 'Gurgaon, Haryana', 'Hyderabad, Telangana',
        'Indore, Madhya Pradesh', 'Jaipur, Rajasthan', 'Kochi, Kerala',
        'Kolkata, West Bengal', 'Mumbai, Maharashtra', 'Noida, Uttar Pradesh',
        'Pune, Maharashtra', 'Remote (India)', 'Vizag, Andhra Pradesh',
    ]

    def __init__(self, model_dir="/content/drive/MyDrive/models/",
                 groq_api_key: str = GROQ_API_KEY):
        self.device    = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        self.model_dir = model_dir

        self.model_path    = os.path.join(model_dir, "convdeepfm_best.pth")
        self.meta_path     = os.path.join(model_dir, "convdeepfm_meta.pth")
        self.encoders_path = os.path.join(model_dir, "label_encoders.pkl")

        self.user_id_map  = {}
        self.job_id_map   = {}
        self.next_user_id = 0
        self.next_job_id  = 0

        self.model_weight = 0.4
        self.skill_weight = 0.6

        # Domains where SKILLS_DATABASE coverage is low — model score drives ranking
        self.NON_TECH_DOMAINS = {
            'HR', 'Marketing', 'Sales', 'Operations', 'Legal',
            'Healthcare', 'Education', 'Hospitality', 'Finance',
            'Accounting', 'Creative', 'Fitness & Wellness', 'Fashion',
            'Nutrition', 'Account Management', 'Consulting',
            'Business Analysis', 'Project Management', 'Product Management',
            'Media & Film', 'Engineering',
        }

        # Groq LLM client
        if groq_api_key and groq_api_key != "YOUR_GROQ_API_KEY_HERE":
            self.groq = GroqLLMClient(api_key=groq_api_key, model=GROQ_MODEL)
            print("✅ Groq LLM client initialised")
        else:
            self.groq = None
            print("⚠️  No Groq API key — LLM parsing disabled (keyword-regex only)")

        self.load_trained_model()

    def load_trained_model(self):
        print("\n" + "=" * 80)
        print("📥 LOADING ConvDeepFM V1 MODEL & ARTIFACTS")
        print("=" * 80)
        self.metadata     = torch.load(self.meta_path, map_location=self.device, weights_only=False)
        bert_model_name   = self.metadata.get('bert_model', 'all-MiniLM-L6-v2')
        self.bert         = SentenceTransformer(bert_model_name)
        self.bert_dim     = self.metadata.get('bert_dim', 384)
        self.model        = ConvDeepFM(
            field_dims=self.metadata['field_dims'],
            deep_dim=self.metadata['deep_dim'],
            embed_dim=self.metadata['embed_dim']
        ).to(self.device)
        self.model.load_state_dict(
            torch.load(self.model_path, map_location=self.device, weights_only=True))
        self.model.eval()
        with open(self.encoders_path, 'rb') as f:
            self.label_encoders = pickle.load(f)
        print("✅ All V1 artifacts loaded!")

    def safe_encode(self, encoder, value):
        try:
            return encoder.transform([value])[0]
        except ValueError:
            val_lower = str(value).lower()
            for cls in encoder.classes_:
                if val_lower in cls.lower() or cls.lower() in val_lower:
                    try: return encoder.transform([cls])[0]
                    except ValueError: pass
            city = val_lower.split(',')[0].strip()
            for cls in encoder.classes_:
                if city and city in cls.lower():
                    try: return encoder.transform([cls])[0]
                    except ValueError: pass
            return 0

    def _bert_encode(self, text):
        return self.bert.encode(
            [text], batch_size=1, show_progress_bar=False,
            convert_to_numpy=True, normalize_embeddings=True)[0]

    def prepare_features(self, user_profile, job):
        x_cat = np.array([
            0,  # user_id  — unseen at inference
            0,  # job_id   — unseen at inference
            self.safe_encode(self.label_encoders['user_education'], user_profile['education_level']),
            self.safe_encode(self.label_encoders['job_type'],       job['job_type']),
            self.safe_encode(self.label_encoders['location'],       job['location']),
        ], dtype=np.int64)

        # For non-tech: LLM-extracted job skills are now in job['skills'],
        # so joining them into job_text gives BERT richer domain vocabulary
        # (e.g. "Patient Care, Obstetrics, MBBS, Laparoscopy") alongside
        # the raw job description. This is the key signal for ConvDeepFM.
        user_text = (user_profile.get('resume_text', '') + " " +
                     " ".join(user_profile.get('skills', [])))
        job_text  = (job.get('full_description', job['description']) + " " +
                     " ".join(job.get('skills', [])))

        user_emb = self._bert_encode(user_text)
        job_emb  = self._bert_encode(job_text)

        # Keep exactly 3 numeric features — the trained ConvDeepFM BatchNorm
        # expects deep_dim=771 (384+384+3). sem_sim is used OUTSIDE the model
        # in the final_score formula, not fed into it.
        numeric = np.array([
            user_profile['experience_years'],
            job['required_experience'],
            user_profile['experience_years'] - job['required_experience'],
        ], dtype=np.float32)

        x_deep = np.concatenate([user_emb, job_emb, numeric]).astype(np.float32)[np.newaxis, :]
        return x_cat, x_deep

    def predict_score(self, user_profile, job):
        x_cat, x_deep = self.prepare_features(user_profile, job)
        x_cat_t  = torch.LongTensor(x_cat).unsqueeze(0).to(self.device)
        x_deep_t = torch.FloatTensor(x_deep).to(self.device)
        with torch.no_grad():
            raw = self.model(x_cat_t, x_deep_t).item()
        return 1 / (1 + np.exp(-raw))

    def recommend_from_resume(self, resume_path, resume_type='pdf', location="India",
                              num_jobs=100, top_k=15, min_skill_match=0.05,
                              site_names=None):
        if site_names is None:
            site_names = ['indeed', 'linkedin']

        print("\n" + "=" * 80)
        print("🚀 STARTING JOB RECOMMENDATION  [Groq LLM + ConvDeepFM V1]")
        print("=" * 80)

        # ── Parse resume ──────────────────────────────────────────────────────
        parser       = ResumeParser()
        user_profile = parser.parse_resume(resume_path, resume_type, groq_client=self.groq)

        if not user_profile['skills']:
            print("\n⚠️  No skills detected — proceeding with domain-only search.")

        # ── Scrape jobs ───────────────────────────────────────────────────────
        processor = JobProcessor()
        raw_jobs  = processor.scrape_jobs(
            location, num_jobs, site_names,
            domains=user_profile.get('domains'),
            domain=user_profile['domain'],
            llm_job_title=user_profile.get('job_title', ''),
        )

        if not raw_jobs:
            print("\n❌ No jobs found!")
            return None

        # Determine domain type BEFORE processing so LLM enrichment can fire
        is_non_tech = user_profile.get('domain', '') in self.NON_TECH_DOMAINS
        print(f"\n   🏷️  Domain type : {'NON-TECH' if is_non_tech else 'TECH'} → LLM skill enrichment runs for ALL domains")

        # LLM enrichment runs for BOTH tech and non-tech.
        # For tech:     regex catches most skills, LLM fills gaps (aliases, new frameworks).
        # For non-tech: LLM is the primary source — SKILLS_DATABASE barely covers it.
        jobs = processor.process_jobs(
            raw_jobs,
            is_non_tech=is_non_tech,
            groq_client=self.groq,   # always pass — LLM enriches all jobs
        )
        if not jobs:
            print("\n❌ No valid jobs after processing!")
            return None

        # ── Score & recommend ─────────────────────────────────────────────────
        print("\n" + "=" * 80)
        print("🎯 GENERATING RECOMMENDATIONS")
        print("=" * 80)

        user_skills_set = set(user_profile['skills'])
        recommendations = []

        # ── Scoring weights ────────────────────────────────────────────────────
        # SKILLS_DATABASE regex is no longer used in scoring.
        # All three signals use LLM-extracted skills (from resume + job desc):
        #
        #   ConvDeepFM  : learned score using BERT embeddings of LLM-enriched text
        #   llm_skill_match : overlap of Groq-extracted resume skills vs job skills
        #   BERT sem_sim : cosine similarity of resume ↔ job BERT embeddings
        #
        # Weights differ only because sem_sim is a stronger absolute signal
        # for non-tech (where even LLM skill overlap can be low for niche roles).
        if is_non_tech:
            mw   = 0.50   # ConvDeepFM
            sw   = 0.15   # LLM skill overlap (lower — niche roles have low overlap)
            semw = 0.35   # BERT sem_sim — primary for non-tech
        else:
            mw   = 0.40   # ConvDeepFM
            sw   = 0.35   # LLM skill overlap — strong signal for tech
            semw = 0.25   # BERT sem_sim — semantic depth beyond keyword overlap

        print(f"\n   ⚙️  Scoring mode : {'NON-TECH' if is_non_tech else 'TECH'}")
        print(f"   Weights : ConvDeepFM={mw}  LLM_skill_overlap={sw}  BERT_sem_sim={semw}")
        print(f"   Signal source : Groq LLM (skills) + Sentence-BERT (embeddings) + ConvDeepFM (model)")

        # Pre-compute user BERT embedding once (reused for every job)
        user_text = (user_profile.get('resume_text', '') + " " +
                     " ".join(user_profile.get('skills', [])))
        user_emb_cache = self._bert_encode(user_text)

        for job in tqdm(jobs, desc="Scoring jobs"):

            # ── LLM skill overlap (replaces DB skill_match) ───────────────────
            # job['skills'] now contains Groq-extracted skills (+ any regex seeds).
            # user_skills_set comes from Groq resume parsing — same vocabulary.
            # Overlap is semantically meaningful because both sides came from LLM.
            job_skills_set = set(s.lower() for s in job['skills'])
            user_skills_lower = set(s.lower() for s in user_skills_set)

            if len(job_skills_set) >= 1:
                intersection  = len(user_skills_lower & job_skills_set)
                skill_match   = intersection / len(job_skills_set)
            else:
                intersection  = 0
                skill_match   = 0.0

            # Loose floor — only drop jobs with zero semantic similarity AND
            # zero skill overlap (truly unrelated). BERT sem_sim handles the rest.
            # No hard filter on skill_match alone since LLM overlap can be low
            # for valid niche roles (e.g. "Obstetrician" vs "Gynaecologist").

            # ── BERT semantic similarity ──────────────────────────────────────
            # LLM-enriched skills are in job['skills'] and joined into job_text,
            # giving BERT real domain vocabulary to embed.
            job_text = (job.get('full_description', job['description']) + " " +
                        " ".join(job.get('skills', [])))
            job_emb  = self._bert_encode(job_text)
            sem_sim  = max(0.0, float(np.dot(user_emb_cache, job_emb)))

            # ── ConvDeepFM model score ────────────────────────────────────────
            # prepare_features internally encodes both BERT embeddings + sem_sim
            model_score = self.predict_score(user_profile, job)

            # ── Final combined score ──────────────────────────────────────────
            final_score = mw * model_score + sw * skill_match + semw * sem_sim

            # ── Experience modifier ───────────────────────────────────────────
            if job['required_experience'] is not None and job['required_experience'] > 0:
                gap = user_profile['experience_years'] - job['required_experience']
                if gap >= 0:
                    exp_mod = 1.15 if gap <= 2 else 1.05 if gap <= 5 else 1.0
                else:
                    exp_mod = max(0.4, 1.0 + gap * 0.08)
            else:
                exp_mod = 1.1
            final_score = min(final_score * exp_mod, 1.0)

            recommendations.append({
                'job':             job,
                'model_score':     model_score,
                'skill_match':     skill_match,
                'sem_sim':         sem_sim,
                'final_score':     final_score,
                'matching_skills': [s for s in job['skills'] if s.lower() in user_skills_lower],
                'missing_skills':  [s for s in job['skills'] if s.lower() not in user_skills_lower],
            })

        recommendations.sort(key=lambda x: x['final_score'], reverse=True)
        recommendations = recommendations[:top_k]

        self._display_results(user_profile, recommendations, location)

        return {
            'user_profile':         user_profile,
            'recommendations':      recommendations,
            'total_jobs_analyzed':  len(jobs),
            'location':             location,
            'timestamp':            datetime.now().isoformat(),
        }

    def _display_results(self, user, recs, location):
        print("\n" + "=" * 80)
        print("🎯 TOP JOB RECOMMENDATIONS")
        print("=" * 80)
        print(f"\n📊 CANDIDATE PROFILE:")
        print(f"   ✓ Skills:     {len(user['skills'])}")
        print(f"   ✓ Experience: {user['experience_years']} years")
        print(f"   ✓ Education:  {user['education_level']}")
        print(f"   ✓ Domain:     {user['domain']}")
        if user.get('job_title'):
            print(f"   ✓ Job Title:  {user['job_title']}")
        print(f"   ✓ Location:   {location}")
        print(f"   ✓ Parsed via: {user.get('parse_source', 'unknown')}")

        if recs:
            model_scores = [r['model_score'] for r in recs]
            skill_scores = [r['skill_match'] for r in recs]
            final_scores = [r['final_score'] for r in recs]
            print(f"\n📈 SCORE DISTRIBUTION:")
            print(f"   Model : {np.min(model_scores):.2f}–{np.max(model_scores):.2f} (avg {np.mean(model_scores):.2f})")
            print(f"   Skill : {np.min(skill_scores):.2f}–{np.max(skill_scores):.2f} (avg {np.mean(skill_scores):.2f})")
            print(f"   Final : {np.min(final_scores):.2f}–{np.max(final_scores):.2f} (avg {np.mean(final_scores):.2f})")

        print(f"\n" + "=" * 80)
        print(f"TOP {len(recs)} JOB RECOMMENDATIONS")
        print("=" * 80)
        for i, rec in enumerate(recs, 1):
            job = rec['job']
            print(f"\n{i}. {job['title']}")
            print(f"🏢 {job['company']}")
            print(f"📍 {job['location']} | {job['job_type']}")
            if job['required_experience'] is not None:
                exp_diff  = user['experience_years'] - job['required_experience']
                exp_emoji = "✅" if abs(exp_diff) <= 2 else "⚠️" if abs(exp_diff) <= 5 else "❌"
                print(f"💼 Experience: {job['required_experience']}yr required {exp_emoji} (You: {user['experience_years']})")
            print(f"📅 Posted: {job['date_posted']}")
            print(f"📊 Final:{rec['final_score']:.1%}  Model:{rec['model_score']:.1%}  Skill:{rec['skill_match']:.1%}  SemSim:{rec.get('sem_sim', 0):.1%}")
            if rec['matching_skills']:
                print(f"✅ Matching ({len(rec['matching_skills'])}): {', '.join(rec['matching_skills'][:5])}")
            if rec['missing_skills'][:3]:
                print(f"📚 To learn: {', '.join(rec['missing_skills'][:3])}")
            print(f"🔗 {job['job_url'][:70]}...")
            print("-" * 80)

# CELL 12: MAIN EXECUTION
# ============================================================================
print("\n" + "=" * 80)
print("✅ ConvDeepFM V1 + Groq LLM JOB RECOMMENDATION SYSTEM READY!")
print("=" * 80)

# Upload resume
print("\n📤 UPLOAD YOUR RESUME (PDF or DOCX)")
print("=" * 80)
uploaded = files.upload()

if uploaded:
    filename  = list(uploaded.keys())[0]
    file_type = filename.split('.')[-1].lower()
    print(f"\n✅ Uploaded: {filename}")

    engine = ConvDeepFMJobRecommender(
        model_dir="/content/drive/MyDrive/models/",
        groq_api_key=GROQ_API_KEY,   # set at top of file or via env var
    )

    result = engine.recommend_from_resume(
        resume_path=filename,
        resume_type=file_type,
        location='India',
        num_jobs=200,
        top_k=40,
        min_skill_match=0.05,
        site_names=['indeed', 'linkedin'],
    )

    if result:
        with open('job_recommendations.json', 'w') as f:
            json.dump(result, f, indent=2, default=str)
        print("\n✅ Results saved to job_recommendations.json")

print("\n" + "=" * 80)
print("🎯 SYSTEM FEATURES:")
print("  ✓ Groq LLM (llama-3.3-70b-versatile) for resume parsing — PRIMARY")
print("  ✓ LLM domain suggestions TRUSTED as-is (LLM ordering preserved)")
print("  ✓ Domain keyword set used ONLY as fallback (LLM unavailable / no valid labels)")
print("  ✓ Keyword-regex fallback for all fields if Groq API unavailable")
print("  ✓ LLM job title detection (always from LLM, no keyword override)")
print("  ✓ ConvDeepFM V1: BERT embeddings (all-MiniLM-L6-v2, 384-dim)")
print("  ✓ Trained on 11,766 samples | experience-gap modifier")
print("  ✓ Real-time job scraping — Indeed & LinkedIn")
print("=" * 80)

